import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes';
import Header from '@/components/Header'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider
       appearance={{
        baseTheme: dark
      }}
      
      >
      <html lang="en">
      
        <body>
        <Header />
      
            {children}
         
        </body>
 
      </html>
    </ClerkProvider>
    </html>
  )
}
